# Generated by Django 4.2.7 on 2024-10-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=15)),
                ('niveau_diplome', models.CharField(choices=[('Baccalauréat', 'Baccalauréat'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
                ('domaine_formation', models.CharField(max_length=100)),
                ('date_obtention', models.DateField()),
                ('niveau_francais', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Courant', 'Courant')], max_length=20)),
                ('niveau_anglais', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Courant', 'Courant')], max_length=20)),
                ('duree_experience', models.IntegerField(help_text='Durée en années')),
                ('disponibilite', models.BooleanField(help_text='Êtes-vous disponible immédiatement ?')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.CharField(choices=[('à distance', 'À distance'), ('En personne', 'En personne')], default='En personne', max_length=25)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('canceled', 'Annulé')], default='pending', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.candidat')),
            ],
        ),
    ]
